steps:
  - name: maven:3.6.0-jdk-11-slim
    entrypoint: 'mvn'
    args: ['clean', 'install', '-DskipTests']
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/fazilk8s:12', '.']
    id: Building the container image
# Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/fazilk8s']
    id: Pushing the image to registry
# Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'fazilk8s', '--image', 'gcr.io/$PROJECT_ID/fazilk8s:12', '--region', 'us-central1', '--platform', 'managed', "--allow-unauthenticated"]
